name: Setup
description: Setup Node.js and install dependencies

runs:
    using: composite
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v5
          with:
              node-version-file: .nvmrc
              cache: yarn
              cache-dependency-path: yarn.lock

        - name: Init submodules
          run: git submodule update --init --recursive
          shell: bash

        - name: Install dependencies
          run: yarn install --immutable
          shell: bash
