/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


#pragma mark - NativeFileHashHashOptions

template <typename P0, typename P1, typename P2, typename P3>
struct NativeFileHashHashOptions {
  P0 key{};
  P1 keyEncoding{};
  P2 seed{};
  P3 mmap;
  bool operator==(const NativeFileHashHashOptions &other) const {
    return key == other.key && keyEncoding == other.keyEncoding && seed == other.seed && mmap == other.mmap;
  }
};

template <typename T>
struct NativeFileHashHashOptionsBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.key)>(rt, value.getProperty(rt, "key"), jsInvoker),
      bridging::fromJs<decltype(types.keyEncoding)>(rt, value.getProperty(rt, "keyEncoding"), jsInvoker),
      bridging::fromJs<decltype(types.seed)>(rt, value.getProperty(rt, "seed"), jsInvoker),
      bridging::fromJs<decltype(types.mmap)>(rt, value.getProperty(rt, "mmap"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String keyToJs(jsi::Runtime &rt, decltype(types.key) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String keyEncodingToJs(jsi::Runtime &rt, decltype(types.keyEncoding) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String seedToJs(jsi::Runtime &rt, decltype(types.seed) value) {
    return bridging::toJs(rt, value);
  }
  static bool mmapToJs(jsi::Runtime &rt, decltype(types.mmap) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    if (value.key) {
      result.setProperty(rt, "key", bridging::toJs(rt, value.key.value(), jsInvoker));
    }
    if (value.keyEncoding) {
      result.setProperty(rt, "keyEncoding", bridging::toJs(rt, value.keyEncoding.value(), jsInvoker));
    }
    if (value.seed) {
      result.setProperty(rt, "seed", bridging::toJs(rt, value.seed.value(), jsInvoker));
    }
    if (value.mmap) {
      result.setProperty(rt, "mmap", bridging::toJs(rt, value.mmap.value(), jsInvoker));
    }
    return result;
  }
};



#pragma mark - NativeFileHashRuntimeDiagnostics

template <typename P0, typename P1, typename P2, typename P3, typename P4>
struct NativeFileHashRuntimeDiagnostics {
  P0 engine{};
  P1 zigApiVersion{};
  P2 zigExpectedApiVersion{};
  P3 zigApiCompatible{};
  P4 zigVersion;
  bool operator==(const NativeFileHashRuntimeDiagnostics &other) const {
    return engine == other.engine && zigApiVersion == other.zigApiVersion && zigExpectedApiVersion == other.zigExpectedApiVersion && zigApiCompatible == other.zigApiCompatible && zigVersion == other.zigVersion;
  }
};

template <typename T>
struct NativeFileHashRuntimeDiagnosticsBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.engine)>(rt, value.getProperty(rt, "engine"), jsInvoker),
      bridging::fromJs<decltype(types.zigApiVersion)>(rt, value.getProperty(rt, "zigApiVersion"), jsInvoker),
      bridging::fromJs<decltype(types.zigExpectedApiVersion)>(rt, value.getProperty(rt, "zigExpectedApiVersion"), jsInvoker),
      bridging::fromJs<decltype(types.zigApiCompatible)>(rt, value.getProperty(rt, "zigApiCompatible"), jsInvoker),
      bridging::fromJs<decltype(types.zigVersion)>(rt, value.getProperty(rt, "zigVersion"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String engineToJs(jsi::Runtime &rt, decltype(types.engine) value) {
    return bridging::toJs(rt, value);
  }
  static double zigApiVersionToJs(jsi::Runtime &rt, decltype(types.zigApiVersion) value) {
    return bridging::toJs(rt, value);
  }
  static double zigExpectedApiVersionToJs(jsi::Runtime &rt, decltype(types.zigExpectedApiVersion) value) {
    return bridging::toJs(rt, value);
  }
  static bool zigApiCompatibleToJs(jsi::Runtime &rt, decltype(types.zigApiCompatible) value) {
    return bridging::toJs(rt, value);
  }
  static jsi::String zigVersionToJs(jsi::Runtime &rt, decltype(types.zigVersion) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "engine", bridging::toJs(rt, value.engine, jsInvoker));
    result.setProperty(rt, "zigApiVersion", bridging::toJs(rt, value.zigApiVersion, jsInvoker));
    result.setProperty(rt, "zigExpectedApiVersion", bridging::toJs(rt, value.zigExpectedApiVersion, jsInvoker));
    result.setProperty(rt, "zigApiCompatible", bridging::toJs(rt, value.zigApiCompatible, jsInvoker));
    result.setProperty(rt, "zigVersion", bridging::toJs(rt, value.zigVersion, jsInvoker));
    return result;
  }
};



#pragma mark - NativeFileHashRuntimeInfo

template <typename P0>
struct NativeFileHashRuntimeInfo {
  P0 engine;
  bool operator==(const NativeFileHashRuntimeInfo &other) const {
    return engine == other.engine;
  }
};

template <typename T>
struct NativeFileHashRuntimeInfoBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.engine)>(rt, value.getProperty(rt, "engine"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String engineToJs(jsi::Runtime &rt, decltype(types.engine) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "engine", bridging::toJs(rt, value.engine, jsInvoker));
    return result;
  }
};


template <typename T>
class JSI_EXPORT NativeFileHashCxxSpec : public TurboModule {
public:
  static constexpr std::string_view kModuleName = "FileHash";

protected:
  NativeFileHashCxxSpec(std::shared_ptr<CallInvoker> jsInvoker) : TurboModule(std::string{NativeFileHashCxxSpec::kModuleName}, jsInvoker) {
    methodMap_["fileHash"] = MethodMetadata {.argCount = 4, .invoker = __fileHash};
    methodMap_["stringHash"] = MethodMetadata {.argCount = 5, .invoker = __stringHash};
    methodMap_["cancelOperation"] = MethodMetadata {.argCount = 1, .invoker = __cancelOperation};
    methodMap_["getRuntimeInfo"] = MethodMetadata {.argCount = 0, .invoker = __getRuntimeInfo};
    methodMap_["getRuntimeDiagnostics"] = MethodMetadata {.argCount = 0, .invoker = __getRuntimeDiagnostics};
  }
  
private:
  static jsi::Value __fileHash(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::fileHash) == 5,
      "Expected fileHash(...) to have 5 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::fileHash,  static_cast<NativeFileHashCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt),
      count <= 2 || args[2].isUndefined() ? std::nullopt : std::make_optional(args[2].asObject(rt)),
      count <= 3 || args[3].isUndefined() ? std::nullopt : std::make_optional(args[3].asString(rt)));
  }

  static jsi::Value __stringHash(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::stringHash) == 6,
      "Expected stringHash(...) to have 6 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::stringHash,  static_cast<NativeFileHashCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
      count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt),
      count <= 2 || args[2].isUndefined() ? std::nullopt : std::make_optional(args[2].asString(rt)),
      count <= 3 || args[3].isUndefined() ? std::nullopt : std::make_optional(args[3].asObject(rt)),
      count <= 4 || args[4].isUndefined() ? std::nullopt : std::make_optional(args[4].asString(rt)));
  }

  static jsi::Value __cancelOperation(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
    static_assert(
      bridging::getParameterCount(&T::cancelOperation) == 2,
      "Expected cancelOperation(...) to have 2 parameters");
    bridging::callFromJs<void>(rt, &T::cancelOperation,  static_cast<NativeFileHashCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule),
      count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt));return jsi::Value::undefined();
  }

  static jsi::Value __getRuntimeInfo(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getRuntimeInfo) == 1,
      "Expected getRuntimeInfo(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getRuntimeInfo,  static_cast<NativeFileHashCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }

  static jsi::Value __getRuntimeDiagnostics(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* /*args*/, size_t /*count*/) {
    static_assert(
      bridging::getParameterCount(&T::getRuntimeDiagnostics) == 1,
      "Expected getRuntimeDiagnostics(...) to have 1 parameters");
    return bridging::callFromJs<jsi::Value>(rt, &T::getRuntimeDiagnostics,  static_cast<NativeFileHashCxxSpec*>(&turboModule)->jsInvoker_, static_cast<T*>(&turboModule));
  }
};

} // namespace facebook::react
