# .github/workflows/publish.yml

name: Publish Package to npm and GitHub Packages

on:
    release:
        types: [created] # Запускать только при создании нового релиза

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write # Даем разрешение на запись в GitHub Packages

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # Устанавливаем Bun для сборки
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Build package
              run: bun run build

            # --- Публикация на NPM ---
            - name: Setup Node.js for npm
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Publish to npm
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            # --- Публикация на GitHub Packages ---
            - name: Setup Node.js for GitHub Packages
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  # URL реестра теперь будет взят из файла .npmrc

            - name: Publish to GitHub Packages
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
